# resources:
# - rollout.yaml
# - service-active.yaml
# - service-preview.yaml
# - virtualservice.yaml


resources:
- app.yaml
- rollout.yaml
- service.yaml
- virtualservice.yaml
- destinationrule.yaml