# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: grafana
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     - repoURL: 'https://grafana.github.io/helm-charts'
#       chart: grafana
#       targetRevision: 8.8.0  # Stable Jan 2026 version
#       helm:
#         valueFiles:
#           - $values/platform/observability/grafana/values.yaml
#     - repoURL: 'https://github.com/ankit96khokhar/gitops'
#       targetRevision: main
#       ref: values
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: istio-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true