# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     - repoURL: 'https://prometheus-community.github.io/helm-charts'
#       chart: prometheus
#       targetRevision: 26.0.0  # Stable version for Jan 2026
#       helm:
#         valueFiles:
#           - $values/platform/observability/prometheus/values.yaml
#     - repoURL: 'https://github.com/ankit96khokhar/gitops'
#       targetRevision: main
#       ref: values
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: istio-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true